import math

print(math.acos(0.55))
print(math.acosh(7))
print("\n--------\n")
print(math.asin(0.55))
print(math.asinh(7))
print("\n--------\n")
print(math.atan(0.55))
print(math.atanh(0.59))
print("\n--------\n")
print(math.cos(0.00))
print(math.cosh(1))
print("\n--------\n")
print(math.sin(0.00))
print(math.sinh(0.00))